name: linting
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar:
    uses: shree-test-org/Centralized-sonarQube-configuration/.github/workflows/sonarqube.yml@main
    secrets: 
      SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}