name: linting
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar:
    uses: subhashree-dhal/Centralized-sonarQube-configuration/.github/workflows/sonarqube.yml@main
    with:
      project-key: shree-test-org_Test-repo-for-sonarqube
    secrets: {inherit}