name: linting
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar:
    uses: your-org/sonarqube-workflows/.github/workflows/sonarqube.yml@main
    with:
      project-key: shree-test-org_Test-repo-for-sonarqube
    secrets: {inherit}